# Generated by Django 4.1.6 on 2023-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TVParser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_url", models.CharField(max_length=100)),
                ("title_text", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
