# Generated by Django 4.1.6 on 2023-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tv_shows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="price",
            field=models.PositiveIntegerField(null=True, verbose_name="Цена билета"),
        ),
    ]
