# Generated by Django 4.1.6 on 2023-02-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tv_shows", "0002_tvshow_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingTv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "choise_show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_object",
                        to="tv_shows.tvshow",
                    ),
                ),
            ],
        ),
    ]
